const slides=[...document.querySelectorAll('.slide')],progress=document.getElementById('progressBar'),pageNum=document.getElementById('pageNum'),sectionName=document.getElementById('sectionName');
let current=Math.max(0,Math.min(slides.length-1,(parseInt(location.hash.replace('#',''),10)||1)-1));
function show(i,push=true){
  current=Math.max(0,Math.min(slides.length-1,i));
  slides.forEach((s,n)=>{s.classList.toggle('active',n===current);s.classList.toggle('past',n<current);s.classList.remove('motion');if(n===current){s.scrollTop=0;requestAnimationFrame(()=>s.classList.add('motion'))}});
  progress.style.width=((current+1)/slides.length*100)+'%';
  pageNum.textContent=String(current+1).padStart(2,'0')+' / '+String(slides.length).padStart(2,'0');
  sectionName.textContent=slides[current].dataset.section||'';
  if(push)history.replaceState(null,'','#'+(current+1));
}
document.getElementById('prev').onclick=()=>show(current-1);document.getElementById('next').onclick=()=>show(current+1);
document.addEventListener('keydown',e=>{if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();show(current+1)}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();show(current-1)}if(e.key==='Home')show(0);if(e.key==='End')show(slides.length-1);if(e.key==='Escape')document.getElementById('menu').classList.remove('open')});
let wheelLock=false;document.addEventListener('wheel',e=>{const s=slides[current],dir=e.deltaY>0?1:-1,canScroll=s.scrollHeight>s.clientHeight+2&&((dir>0&&s.scrollTop+s.clientHeight<s.scrollHeight-2)||(dir<0&&s.scrollTop>2));if(canScroll)return;if(wheelLock||Math.abs(e.deltaY)<25)return;wheelLock=true;show(current+dir);setTimeout(()=>wheelLock=false,650)},{passive:true});
let touchX=0,touchY=0;document.addEventListener('touchstart',e=>{const t=e.changedTouches[0];touchX=t.clientX;touchY=t.clientY},{passive:true});document.addEventListener('touchend',e=>{const t=e.changedTouches[0],dx=t.clientX-touchX,dy=t.clientY-touchY;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.35)show(current+(dx<0?1:-1))},{passive:true});
document.getElementById('fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
const menu=document.getElementById('menu'),list=document.getElementById('menuList');slides.forEach((s,i)=>{const b=document.createElement('button');b.innerHTML='<b>'+String(i+1).padStart(2,'0')+'</b>'+(s.dataset.section||'');b.onclick=()=>{menu.classList.remove('open');show(i)};list.appendChild(b)});document.getElementById('menuOpen').onclick=()=>menu.classList.add('open');document.getElementById('menuClose').onclick=()=>menu.classList.remove('open');menu.addEventListener('click',e=>{if(e.target===menu)menu.classList.remove('open')});show(current,false);
const c=document.getElementById('heat'),ctx=c.getContext('2d');let W,H,dpr,particles=[];function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*dpr;c.height=H*dpr;c.style.width=W+'px';c.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0);particles=Array.from({length:Math.max(18,Math.floor(W/68))},()=>spawn(true))}function spawn(randomY=false){return{x:W*(.62+Math.random()*.42),y:randomY?Math.random()*H:H+20,r:.7+Math.random()*1.7,vx:-.12-Math.random()*.28,vy:-.22-Math.random()*.7,a:.07+Math.random()*.24,life:Math.random()*320}}function frame(){ctx.clearRect(0,0,W,H);particles.forEach((p,i)=>{p.x+=p.vx;p.y+=p.vy;p.life++;if(p.y<-25||p.x<W*.48||p.life>540)particles[i]=p=spawn(false);ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle='rgba(255,'+(100+Math.floor(Math.random()*50))+',40,'+p.a+')';ctx.fill()});requestAnimationFrame(frame)}if(!location.search.includes('static')){addEventListener('resize',resize);resize();frame()}else{c.style.display='none'}
